### ISSUE TITLE
TODO - Things to do

### ISSUE THREAD

**Issue by amsesk** [amsesk/scgid#1]
**For Release 1.0.0**
- [x] Implement plotly-python GCT plots
- [ ] Expand test suite to completion
    - [ ] build_taxdb.py
    - [x] codons.py
    - [ ] config.py
    - [ ] consensus.py
    - [ ] db.py
    - [ ] dependencies.py
    - [ ] error.py
    - [x] flexwindow.py **(does not yet test data where trade-off values change results.)**
    - [ ] gct.py
    - [x] infotable.py
    - [ ] kmers.py
    - [ ] library.py
    - [ ] main.py
    - [ ] modcomm.py
    - [ ] module.py
    - [ ] parsers.py
    - [ ] plotter.py
    - [ ] reuse.py
    - [ ] sequence.py
- [ ] Relax format restrictions of spexpand to allow new lines and extra tabs/spaces
- [ ] Allow module objects to be called externally as library-like elements (i.e., things like `get_head()` need to failable and recoverable
- [ ] Correctly implement SCGidUpdater
- [ ] Log command line and subprocess error correctly
- [ ] Update docs with info about spdbify and implement in python instead of rust
- [ ] NoTargetError raised in flexwindow.py is not appropriate for all the times it is raised, needs to be subdivided into different error classes
- [ ] FlexibleSelectionWindows behave unexpectedly when target means are sufficiently distorted by outlying high/low values. Can lead to 0-width window axes that stall gct. Current fix deletes these windows from analysis, but a more thorough fix should remove outliers in these cases. **This should also make windows better.**
- [ ] SCGid.Codons.Annotate blastn command doesn't log blastn call errors
- [ ] Add information about -s flag in `scgid kmers annotate` with examples
